### PR TITLE
Batch system checks nonces, and remove unnecessary error message

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Starting a batch job now checks for a nonce, to verify its really the user who initiated this request. 
Also, `EE_Admin_Page::add_query_args_and_nonce()` gives a warning if no URL is provided, but that seems unnecessary: we are successfully using it with no problem (eg `\Registrations_Admin_Page::_registrations_report_base()`), it generates a nonce ok without it, and `add_query_arg`, which it calls, just uses the current URL instead (but maybe there's something I'm overlooking). FYI that check was originally from 943c7f41bb2e2bc90
The latter change will help with https://github.com/eventespresso/eea-importer/pull/57/files

## How has this been tested

* [x] Generate a registrations CSV report. I should still work fine
* [x] Try again, but when the batch job starts, quickly look at the current page's URL, find where it says `&default_nonce=...` and delete a character from the nonce's value and hit enter to visit that modified URL. You should be told the nonce failed.
* [x] Use all the links that you know use the batch system (eg, ones I can think of are: contact list CSV report and multisite migration/update assessment) they should all work like before

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by mnelson4** [comment]
@lorenzocaum do you mind testing this branch with https://github.com/eventespresso/eea-importer/pull/57 to verify that issue is resolved?
After that, @joshfeck or yourself should double-check the other testing notes

**Comment by lorenzocaum** [comment]
Hey Mike, I checked these:

- Registration report
- All registrations report
- Filtered registration report
- Contact list report

Then I tested with the Importer. I did not test the multisite assessment as I don't have that running on my testing site.

@garthkoyle Could you test this out please?

https://github.com/eventespresso/event-espresso-core/pull/1343#issue-288966157

**Comment by garthkoyle** [comment]
When I test a filtered registration report this is the url:

```https://garth.eventespresso.com/wp-admin/admin.php?page=espresso_batch&use_filters=1&return_url=%2F%2Fgarth.eventespresso.com%2Fwp-admin%2Fadmin.php%3Fs%3D%26_wpnonce%3D3f15ce8d38%26_wp_http_referer%3D%252Fwp-admin%252Fadmin.php%253Fpage%253Despresso_registrations%26action%3D-1%26month_range%3D%26EVT_CAT%3D-1%26_reg_status%3DRAP%26page%3Despresso_registrations%26route%3Ddefault%26perpage%3D100%26approve_registrations_nonce%3Dd9a2a19c9e%26approve_and_notify_registrations_nonce%3D7e8963a84b%26decline_registrations_nonce%3D89230f0543%26decline_and_notify_registrations_nonce%3Da7e96c5ce9%26pending_registrations_nonce%3D8ff2943813%26pending_and_notify_registrations_nonce%3Df9fc65711a%26no_approve_registrations_nonce%3D8f943669e4%26no_approve_and_notify_registrations_nonce%3D17963cbd38%26cancel_registrations_nonce%3D13145a6c5b%26cancel_and_notify_registrations_nonce%3D41fc97e21c%26trash_registrations_nonce%3D4fdf1d36b3%26paged%3D1%26action2%3D-1%26default_nonce%3D178918d3&filters=a%3A5%3A%7Bi%3A0%3Ba%3A1%3A%7Bs%3A6%3A%22STS_ID%22%3Bs%3A3%3A%22RAP%22%3B%7Ds%3A4%3A%22caps%22%3Bs%3A10%3A%22read_admin%22%3Bs%3A24%3A%22default_where_conditions%22%3Bs%3A15%3A%22this_model_only%22%3Bs%3A8%3A%22order_by%22%3Ba%3A2%3A%7Bs%3A8%3A%22REG_date%22%3Bs%3A4%3A%22DESC%22%3Bs%3A6%3A%22REG_ID%22%3Bs%3A4%3A%22DESC%22%3B%7Ds%3A5%3A%22limit%22%3Ba%3A2%3A%7Bi%3A0%3Bi%3A0%3Bi%3A1%3Bi%3A10%3B%7D%7D&action=default&registrations_report_nonce=28e24bd7ac&return=-1&batch=file&job_handler=EventEspressoBatchRequest%5CJobHandlers%5CRegistrationsReport&default_nonce=11d78918```

There are a lot of nonces in that url, is that right? 

When I did edit the last nonce url parameter, it said the job had expired.

**Comment by joshfeck** [comment]
I also tested the check-ins page's reports.

@mnelson4 this is ready for merging, but maybe you can reply to @garthkoyle's question about the multiple encoded nonces.

**Comment by mnelson4** [comment]
Thanks @josh. Oh dang I thought I had replied, but obviously not.

That issue is reproducible on master. Just filter for approved registrations, or really anything. But those extra nonces don't affect this work. Shall we create a different issue for that?

**Comment by joshfeck** [comment]
> Shall we create a different issue for that?

Only if it's a problem that needs fixing.

**Comment by mnelson4** [comment]
I don’t think it’s creating any problems- we are still very far from the URL length limit. It’s just s little messy looking

**Pull request merged**
