### PR TITLE
Remove monster sideload error

### PR DESCRIPTION
**Pull request by joshfeck**
Please see https://events.codebasehq.com/projects/event-espresso/tickets/10757 for backstory
## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

It's a simple test: 

1. Set WP_DEBUG to true
2. Go to WP > Settings > General and set the site language to a language that has no language files here: https://github.com/eventespresso/languages-ee4

This branch simply removes the response output but keeps the path part of the message. Which is usually sufficient for troubleshooting this.

### CODE REVIEW

**Comment by kristinoc** [comment]
Changed it to site language > "Cebuano" and it presented this error:
language error

**Comment by Pebblo** [comment]
@kristinoc you sure you're on the correct branch?

The error in your screenshot is the 'old' error, the first line should now read:

> Unable to upload the file. Either the path given to upload from is incorrect, or something else happened. Here is the path given:

The above looks like it's from master branch.

**Comment by kristinoc** [comment]
I was in the master branch.   how do i determine which branch to pull when viewing a ticket?

**Comment by kristinoc** [comment]
tested again - this time in my staging [not my local dev site] per @joshfeck 
and received no error

**Comment by kristinoc** [comment]
tested and it presented brief text with path as expected -- not monster error.
language error2

**Pull request merged**
