### PR TITLE
Improve redirects on trash/restore/delete for registration list table (fixes #898)

### LINKED ISSUE #898: Return to current list of registrations after trashing a registration
This was originally reported in codebase in [8699](https://events.codebasehq.com/projects/event-espresso/tickets/8699) where @lorenzocaum outlined these steps:

> 1) Go to Event Espresso --> Events
> 
> 2) Look for an event and hover over the name and click on Registrations
> 
> 3) You'll now be viewing a list of registrants for this specific event
> 
> 4) Trash a registrant by hovering over their name and clicking on Trash
> 
> Event Espresso will trash the registrant and you'll be taken to the registrations overview screen for all events.

Further clarification: The same result will happen if you do a bulk trash (check boxes and apply bulk "Trash" action). The desired result, where you're returned to the list of registrations for the event, happens if you bulk "Cancel" registrations.

### PR DESCRIPTION
**Pull request by nerrad**
## Problem this Pull Request solves

See #898 for original report.  This pull adds the following:

- Extract request param merge with new route info to its own method in `EE_Admin_Page`
- Implement the above where we want this behaviour.
- Ensure action links in the registration list table correctly include the EVT_ID if action link if it is present in the request.

## How has this been tested

* [x] When you trash a registration from a filtered registration list table view (by event) it should redirect to the same filtered view after trashing.
* [x] Same for restoring a registration.
* [x] Same for deleting a registration.
* [x] Behaviour should only occur on filtered registration view by event.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by tn3rb** [comment]
nice. there's likely a few other places this same kind of enhancement can be applied, but that's another issue(s)

**Comment by joshfeck** [comment]
This is a big improvement. I did find that when I perm. delete a registration (from the filtered event's trash view) the redirect went to the main registrations list. Is that expected? The third item in the testing checklist seems to indicate it's not.

**Comment by nerrad** [comment]
> This is a big improvement. I did find that when I perm. delete a registration (from the filtered event's trash view) the redirect went to the main registrations list. Is that expected?

Nope not expected.  I missed one spot where the request args needing merging with the action for the redirect.

**Comment by joshfeck** [comment]
thumbs up emoji

**Pull request merged**
