### PR TITLE
Fix Message Preview

### LINKED ISSUE #3604: Fix sending test messages
Try and send a test email from any message type and you'll see:

> The following errors have occurred:
> Missing necessary parameters for displaying preview
> Messages_Admin_Page - _preview_message - 2154
> Unable to generate preview because of invalid data
> EE_Messages_Processor - generate_for_preview - 387
> The test message was not sent
> Messages_Admin_Page - _do_test_send - 3072

**Describe the bug**
Go to Event Espresso -> Messages -> Default Message Templates -> Reg Approved -> Edit Registrant.

In the sidebar to the right, add an email address to send a test email to and hit send.

You'll get the above errors.

### PR DESCRIPTION
**Pull request by tn3rb**
This PR:

- closes #3604 
- fixes parameter prefixes

### CODE REVIEW

**Comment by tn3rb** [comment]
changes look good... you'll have to re-approve the changes. I can't since i'm the PR author.

**Review by Pebblo — APPROVED** [review]

**Comment by tn3rb** [comment]
with this branch I now see the following notices at the top of the message preview:

```
Notice: Undefined variable: message_type in 
/admin_pages/messages/Messages_Admin_Page.core.php on line 2195

Notice: Undefined index: in 
/admin_pages/messages/Messages_Admin_Page.core.php on line 2195

Notice: Trying to get property 'label' of non-object in 
/admin_pages/messages/Messages_Admin_Page.core.php on line 2195

Notice: Trying to access array offset on value of type null in 
/admin_pages/messages/Messages_Admin_Page.core.php on line 2195
```

**Comment by tn3rb** [comment]
fix looks good 👍🏻

**Comment by Pebblo** [comment]
Woop, thanks bud.

**Pull request merged**
