### PR TITLE
Fixed "You need to select a ticket quantity" error so it displays to logged-out users

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

https://github.com/eventespresso/event-espresso-core/issues/595
When a logged-out selected to register for an event, but forgot to select a ticket quantity, the error message wouldn't display for them (it did for logged-in users still). This fixes is so it will also be displayed to them.
## How has this been tested

* [x] Log out from the site. Go to an event page. Click "Register Now" *without* selecting a quantity. You should see a helpful error message pointing you need to select a ticket quantity (on master you wouldn't)
* [x] Log in and repeat the above test. Double-check I didn't bork that somehow
* [ ] Other tests you'd suggest @tn3rb? (eg, if I accidentally made it so the session ALWAYS got saved, what symptoms would we see?)

## Checklist

* [ ] I have added a changelog entry for this pull request -> not doing this anymore, as I understand it
* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by joshfeck** [comment]
I tested this and the results of the testing are good. This is ready for merging.

**Comment by mnelson4** [comment]
resolves #595

**Comment by mnelson4** [comment]
fixes #595

**Comment by mnelson4** [comment]
utterly demolishes, salts the fields of, and cuts off the posterity of (but doesn't automatically close) #595

**Pull request merged**
