### PR TITLE
Deprecate html_other_attributes

### PR DESCRIPTION
**Pull request by raphaelkross**
## Problem this Pull Request solves
Solves https://github.com/eventespresso/event-espresso-core/issues/1449 deprecating the `html_other_attributes` and using `other_html_attributes` instead

## How has this been tested

Nothing should change at custom HTML attributes since we're only migrating the functions being used.

To test nothing changed, there's one case that used the old method and now is using the new one:

- Go to Checkout page of any event
- At info section, expand the Add New State/Provincy
- The field `New State/Province Abbreviation *` should have a `size="24"` HTML attribute.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by sethshoultes** [comment]
Here's what I see when viewing the source of the page in Google Chrome:
image

**Comment by mnelson4** [comment]
@sethshoultes what do you see on master? (FYI I don't see that red text on Chrome, and I don't see why it's being highlighted, I don't see what's wrong with it.)

**Comment by sethshoultes** [comment]
@mnelson4 here's master:
image

Maybe we need to add a space between `style=""` and `"size="24"`?

**Comment by joshfeck** [comment]
> Maybe we need to add a space between style="" and size="24" in this branch?

Can you check into this @raphaelkross ?

**Comment by raphaelkross** [comment]
@tn3rb @joshfeck added an extra spacing when the other_attributes is not empty, this should be enough to add the required spacing.

**Pull request merged**
