### PR TITLE
Don't double-URL-encode query parameters

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Don't URL-encoding the credentials sent to PayPal twice (doesn't actually fix https://github.com/eventespresso/event-espresso-core/issues/1289 because PayPal seems to have an internal error when we send an API username with a plus symbol in it)

## How has this been tested

* [x] Set up PayPal with a sandbox account that has a + in its API username, and try to pay with PayPal Pro. You should get a 10004 error (Internal error) instead of "Your PayPal API credentials appear to be invalid. PayPal said "Security header is not valid (10002)". While not a ton better, at least the problem is on PayPal's end, not ours.
* [x] Pay using an account that doesn't have a + in its API username
* [ ] Pay using an account that has other interesting but valid characters in the API username (eg maybe accented characters)

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by mnelson4** [comment]
I hope it's ok I'm passing to you @lorenzocaum to test seeing how you originally reported you.

**Comment by lorenzocaum** [comment]
Hey Mike, when I use the account that has the plus, then I get an 10004; Internal Error after making a payment.

When I swap to the account without the plus, then it works.

Do you see that 10004 on your end?

**Comment by mnelson4** [comment]
Hi @lorenzocaum yeah actually I was getting that too (some details in the first testing note). I had my fingers crossed that it was just some problem with my setup but it sounds like it isn't. 
So, I think this branch solves the problem on OUR end, but it appears there's still a problem on PayPal's end.
So I think we'll just need to report this to PayPal somehow, I don't see how we can avoid passing the user's credentials... I'm pretty sure their response will primarily be "don't use plus signs in your email"...

**Comment by lorenzocaum** [comment]
Hey Mike, since it is out of our control, then what about leaving it as-is?

I checked with the customer that mentioned this and they created another sandbox account to get around it. I also suggested PayPal Smart Buttons since they had access to that extension as well.

**Comment by mnelson4** [comment]
I'd slightly prefer to include this change. It actually does appear to fix the issue ON OUR END (but it appears PayPal still chokes on plus signs, for PayPal Express and PayPal Pro too). It's possible that URL encoding the credentials TWICE may cause problems with other characters too (but not I haven't confirmed that). The only downside is that it takes a little bit of effort to test for regression, and it is possible there's some problem with this I don't see. But in my best judgment, this looks like an improvement. 

And it might be good to document that having plus signs in account IDs is a problem. 

Or we could do all the following only after this gets reported again, and is shown to not be an isolated issue.

My suggestion is to move ahead with this (just test it doesn't cause any regressions).

Thoughts @lorenzocaum, @joshfeck ?

**Comment by joshfeck** [comment]
Yes I think you've identified a problem that needs to be fixed (instead of the double encoding, it should really be encoded once).

**Comment by mnelson4** [comment]
Thanks Josh. So ya @lorenzocaum I say let's just verify this doesn't cause any regressions with what's already working (see testing notes)

**Comment by mnelson4** [comment]
Hey @lorenzocaum I've updated the testing notes to reflect the new expectation that this (unfortunately) only switches the error from a 10002 error (bad credentials, ie our mistake) to a 10004 error (internal server error, ie a problem in PayPal). So if you get a chance to assert the testing notes are passing, we can merge this into master.

**Comment by lorenzocaum** [comment]
Hey Mike, I tested with a plus symbol and saw the 10004 error.

Then I tested without it and the payment worked.

On the last item, when I try to set up a new account with an accented character, then it doesn't let me save the account:

Image 2019-07-15 at 2 46 27 PM

I tried a few accented characters. I think we can move forward and merge this in.

**Pull request merged**
