### PR TITLE
Remove Joyride

### PR DESCRIPTION
**Pull request by hoseinrafiei**
Related to https://github.com/eventespresso/event-espresso-core/issues/3973.

Removed the `core/admin/assets/ee-help-tour.js` file.
Removed whole `core/third_party_libs/joyride` directory.
Removed the instances of joyride in docs, credits and codes.

Also I checked the backend menus to make sure there is no console error but deeper test should be done after code review.

### CODE REVIEW

**Comment by hoseinrafiei** [comment]
@tn3rb

Please check this branch. Do you think it's safe to remove `core/admin/assets/ee-help-tour.js` file.
I searched the codes and found no usage instance for this file.

**Review by tn3rb — COMMENTED** [review]
hmmm... i see six scripts deleted, but only one call to `wp_register_script()` to removed...
can you search some more for those script names and see if they are not referenced anywhere else?

As well, there is likely some corresponding HTML/PHP that goes along with those (although you may have already removed most of that) but can you search for any of that as well?

**Comment by majidabbasi96** [comment]
@hoseinrafiei, the code looks fine. But about the usage, I am not sure whether it is safe or not to remove it.

**Comment by hoseinrafiei** [comment]
@tn3rb

> hmmm... i see six scripts deleted, but only one call to `wp_register_script()` to removed...
> can you search some more for those script names and see if they are not referenced anywhere else?

Rest of them did not registered to the WordPress queue at all.

> As well, there is likely some corresponding HTML/PHP that goes along with those (although you may have already removed most of that) but can you search for any of that as well?

Joyride seems to be related to the Help Tours that we removed all of them couple of months ago so I wasn't able to find any more related HTML and PHP codes. Do you want me to search something more specific?

**Comment by tn3rb** [comment]
ok that's fine, if you have double checked, then that's good enough.

**Review by tn3rb — APPROVED** [review]
# 💯

**Comment by hoseinrafiei** [comment]
@Saam01 

Please checkout this branch and test the EE backend menus to make sure they work as expected.
Also please keep your browser console open to see if you faced any JS issue.

**Comment by Saam01** [comment]
EE backend menus working fine.
But I found error under Page editor (Pages > Edit/create a new page): 

image

**Review by majidabbasi96 — APPROVED** [review]

**Comment by hoseinrafiei** [comment]
> EE backend menus working fine. But I found error under Page editor (Pages > Edit/create a new page)

@Saam01 
This issue is not related to the change of this branch. Please open a new Github issue for this.

**Pull request merged**
