### PR TITLE
Fix issue of storing admin label of questions.

### PR DESCRIPTION
**Pull request by hoseinrafiei**
Fixes https://github.com/eventespresso/event-espresso-core/issues/3792 issue.

### CODE REVIEW

**Comment by hoseinrafiei** [comment]
@mohdshakeel Please test the issue on `fix/question-admin-label` PR and let me know the results.

**Comment by mohdshakeel** [comment]
Thanks, Its working perfect now.

**Comment by hoseinrafiei** [comment]
@tn3rb Could you please check and confirm the changes?

**Review by tn3rb — APPROVED** [review]
# 👌🏻

**Pull request merged**
