### PR TITLE
dont change private events to sold out beceause then they are no longer private

### PR DESCRIPTION
**Pull request by mnelson4**
…

## Problem this Pull Request solves

Fixes private events becoming public when sold out. Instead, they retain the status "private" and are just marked "inactive". See https://github.com/eventespresso/event-espresso-core/issues/278

## How has this been tested

* [x] Create a private event, set the ticket quantity to 1, register for that ticket. Verify the event is still not visible to unauthenticated users. In the WordPress dashboard, the event's "active status" will still appear as "upcoming". Oh well.
* [ ] Possible bug in master: change the registration to "declined". The event's "active status" will still be "upcoming".
* [x] Repeat the above, but with a regular event. It should be marked sold out as normal.

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by mnelson4** [comment]
Kk, although in the course of playing with this, I noticed once a private event's tickets were all sold, its active status was stuck as "inactive" (even when I declined the registrations). I noticed a spot in the code where we were solely looking for published events, but I think we should also be looking for private events. Now, when you declined the registration that sold out the private event, the event's "active status" will be "upcoming". Also, when a private event sells out, its active status just remains "upcoming"... This is just an improvement (not complete fix), so I'm not too fussy about that personally...

**Comment by mnelson4** [comment]
oh and regarding the rant: thanks for bringing that up, although I'd need to immerse myself more in the topic to have anything useful to say. :no_mouth:

**Comment by mnelson4** [comment]
thanks @tn3rb, passing for testing

**Comment by joshfeck** [comment]
This is tested and ready for merging.

**Pull request merged**
