### PR TITLE
dont try to send messages while in full maintenance mode

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

https://github.com/eventespresso/event-espresso-core/issues/500
Fixes error when trying to send messages in full maintenance mode.

## How has this been tested

* [ ] verify that when you register for an event, messages get sent out as normal
* [ ] see testing instructions from Tony on https://github.com/eventespresso/event-espresso-core/issues/500 (although I wasn't able to reproduce the original issue (I actually didn't never saw the messages code get called while in maintenance mode; possibly it got coincidentally fixed, but more likely I just can't reproduce)

## Checklist

* [ ] I have added a changelog entry for this pull request
* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by mnelson4** [comment]
hey @Pebblo while we're waiting for Darren to get back, can you double-check you can still reproduce this issue to confirm this fix is needed?

**Comment by mnelson4** [comment]
Yeah, using this logic whenever `is_locked` is called makes sense. What about having a new method, `can_send_messages()` or something, that checks `is_locked` and `models_can_query()`, and we use that in place of `is_locked`? 
Placing this logic inside `is_locked` would be a bit unexpected for me, but I do like how DRY it is. But if you feel this logic is more at home in `is_locked()` than  new method named something like `can_send_messages()`, then I'll go with that.

**Comment by nerrad** [comment]
In this case I think `is_locked` is okay because the purpose of `is_locked` is to check whether _something_ has locked the messages and preventing them from generating or sending (depending on the "type" passed in as an argument).  By putting the `models_can_query` checked in this method we're including that in the requirements for whether its considered "locked" or not (and also it'd be a requirement that can't be overridden).

**Comment by mnelson4** [comment]
passing to @Pebblo for testing, see original PR description for testing notes

**Comment by sethshoultes** [comment]
@Pebblo are you planning on testing this or would you like someone else to test?

**Comment by Pebblo** [comment]
All good, no more fatal and messages send as normal when not in MM.

**Pull request merged**
