### PR TITLE
Add filter hooks to allow for changing the way prices are displayed on the attendee information step

### PR DESCRIPTION
**Pull request by joshfeck**
## Problem this Pull Request solves

Sometimes people do not want to include the surcharge in the attendee information's ticket table. These filter hooks allow for changing this.

## How has this been tested

- [x] Verify no change to the appearance of the attendee information step's ticket information table
- [ ] test one of the filter hooks with a code snippet like this
```
add_filter(
    'FHEE__EE_Default_Line_Item_Display_Strategy___item_row__unit_price',
    'my_change_ticket_row_price',
    10,
    3
);
function my_change_ticket_row_price($unit_price, $line_item, $tax_rate) {
    $unit_price = EEH_Template::format_currency(
        $line_item->ticket()->base_price()->amount(),
        false,
        false
    );
    return $unit_price;
}
```

- [ ] with the above code snippet activated, a ticket with a price modifier will display the unmodified (or base) price

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by joshfeck** [comment]
follow up when included in a release:
https://eventespresso.com/topic/displaying-surcharge-in-checkout-payment-option-page/#post-296738

**Comment by sethshoultes** [comment]
@joshfeck I am unable to get the example filter working. I still see the surcharge after applying the code snippet:
image

**Comment by joshfeck** [comment]
@sethshoultes the filter hooks in question are applied on the Attendee Information step. The Payment Options step uses a different line item display strategy. I'm planning on adding some other hooks for that other display strategy, but that will be in a separate pull.

**Comment by sethshoultes** [comment]
Oh, so this step?:
image

**Comment by joshfeck** [comment]
That's the step! It doesn't look like something is set up on your site to allow the filter to work. 

I checked on another site and it's removing the surcharge as expected there. You can see an example by starting a registration on this event:
https://josh.eventespresso.com/events/surcharge-ticket/

**Comment by sethshoultes** [comment]
Strange. I see it on your site. Want @Pebblo to test as well?

**Comment by Pebblo** [comment]
The filter works fine for me - https://monosnap.com/file/ZHwVwaTQy3tjn53OzK7EX89FTiBt3m

Obviously total isn't 'correct' with this but we'd need another filter for that either way.

**Pull request merged**
