### PR TITLE
pass currency code for AIM

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

See https://github.com/eventespresso/event-espresso-core/issues/579

It seems AIM added support for passing currency back in 2013, see https://community.developer.authorize.net/t5/Integration-and-Testing/Multi-currency-support/td-p/34758

However, it's not clear if they allow you to pass a currency that's different from the Authorize.net account's currency. https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Authorize-Net-UK-Europe-Update/ba-p/35957 says 
> One gateway account is required for each currency

and https://community.developer.authorize.net/t5/Integration-and-Testing/Multi-currency-support/m-p/34765/highlight/true#M19188 says 

> Authorize.Net is fully live with GBP, Euros, CAD and USD but we currently do not support multi-currency in one account. If a merchant wants to accept multiple currencies, example GBP and EUR, the merchant will need two Authorize.Net Payment Gateway accounts one for GBP and another for EUR transacting merchants.

## How has this been tested

* [x] Make a payment with AIM while country is set to USA
* [x] Make a payment with AIM while country is set to Canada (it won't work because AIM sandbox only works with USD)
* [ ] I'd like the customer who thinks they're setup for multi-currency to validate this works for them before we make this change. Because like I noted on the related ticket, it's possible some users are relying on the existing behaviour (eg, their Authorize.net account is setup for CAD but their country in EE is still the USA default; so currently they're receiving funds in CAD but this change will make them start receiving funds in USD, or make payments stop entirely, which they might not expect.)

## Checklist

* [ ] I have added a changelog entry for this pull request
* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by mnelson4** [comment]
@lorenzocaum would you like to test this? (See https://github.com/eventespresso/event-espresso-core/pull/591#issue-202341496 under "How has this been tested" for testing notes.)
It would be nice to have the user with the issue test it too... maybe I could cherry pick these commits into eventsmart after initial testing, so they can do that.

**Comment by lorenzocaum** [comment]
Hi Mike, I ran the first two tests:

- Test Authorize.net with base of operations for United States
- Test Authorize.net with base of operations for another country. I used Canada.

Both worked as expected and on the second one, I saw reason code 39 (https://cl.ly/242l2x272g2B).

Lets work on the cherry pick for the commit to ES tomorrow.

**Comment by mnelson4** [comment]
@lorenzocaum would you like to wait on the customer confirming this helps them before merging to master?

**Comment by lorenzocaum** [comment]
Yes, that plan sounds good. I followed up with them yesterday and I'm waiting to hear back.

**Comment by mnelson4** [comment]
On https://github.com/eventespresso/eventsmart.com-website/issues/64#issuecomment-410313267 @lorenzocaum noted the customer seems to have abandoned trying to use two currencies from one Authnet account. So the feature they wanted doesn't seem possible.
So, does this PR still have a purpose? I think so: if folks setup their Authnet account to use Euros, and then they setup EE to charge in USD, it will come as a surprise to attendees when they intended to pay $10 USD and are instead charged 10 Euros. On this branch, they will instead get an error. IMO it's better to have an error than unexpectedly pay double.
So @lorenzocaum let's merge this to EE master?

**Comment by lorenzocaum** [comment]
Hi Mike, yes please merge this in because as you mentioned, it will still be helpful.

**Pull request merged**
