### PR TITLE
Use wp default link text color for better a11y

### PR DESCRIPTION
**Pull request by joshfeck**
## Problem this Pull Request solves

The registration admin page has a link that says "edit the above question group" and its color contrast does not pass WCAG. Removing the class that hooks to gray text allows for WCAG compliant link text.

## How has this been tested

load up the registration admin page for a single registration that has custom questions. The link text should have easier to read text.
## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by nerrad** [comment]
For history purposes (especially things like this pull).  It'd be good to have before & after screenshots that visually represent the change.

**Comment by joshfeck** [comment]
Screenshot of before:
screen shot 2019-02-18 at 11 19 27 am

and after:
screen shot 2019-02-18 at 11 18 39 am

**Comment by kristinoc** [comment]
@joshfeck 
I'm not sure the process you need for me to follow to test this?

**Comment by joshfeck** [comment]
No worries, here's a checklist:

- [ ] Switch to branch BUG/edit-answer-group-link-a11y
- [ ] Go to Event Espresso > Registration Form, and add a new question
- [ ] Go to Event Espresso > Registration form > Group > Add new group and check the box next to the question added in step 2
- [ ] Go to add or edit an event and check the boxes next to your new question group (in the Questions Meta box)
- [ ] Register for the event
- [ ] Go to Event Espresso > Registrations and click to view the registration you just made
- [ ] compare the link that says "edit the above question group" with the above screenshots; the testing branch should have blue link text, not light gray
- [ ] editing the answer should work just like it does with the current version of EE4.

**Comment by kristinoc** [comment]
Tested - here is what i see
bug-tix964

**Pull request merged**
