### PR TITLE
Remove Ticket Selector Typing

### PR DESCRIPTION
**Pull request by tn3rb**
Seeing #3619 made me realize that #3617 also used PHP 7+ type hinting so best to remove that before it becomes an issue.
Also noticed some variables that could potentially cause undefined issues, so fixed that too.

### CODE REVIEW

**Comment by knazart** [comment]
Huh, ok. This now raises a question - do we stick to the same min PHP version with add-ons as well ?

**Review by knazart — APPROVED** [review]
Looks good.

**Comment by Pebblo** [comment]
I got a fatal on this branch on PHP5.6.40 so went back through the changes and spotted type hinting in RequestSanitizer so I've also removed those.

Merging this in as no more fatal.

**Comment by tn3rb** [comment]
re: 
>  do we stick to the same min PHP version with add-ons as well ?

no i don't think so. This was only done because the code in question could be going out the door real soon.

Once EDTR is released, our min PHP version needs to be bumped to 7.1 and I don't think there is any reason not to do so with any add-ons as well.

**Pull request merged**
