### PR TITLE
Master

### PR DESCRIPTION
**Pull request by nickheyvaert**
Function should return instead of echo to be able to apply FHEE__EE_Admin_List_Table__single_row_columns__column_{$column_name}__co
lumn_content filter in EE_Admin_List_Table.core.php.

### CODE REVIEW

**Comment by mnelson4** [comment]
thanks @nickheyvaert ! 
Passed this to Darren for review, as he's our admin integration expert.

**Comment by nerrad** [comment]
Thanks Nick, just letting you know I've seen this.  I don't have the time free to review right away but do hope to get to it this week.

**Comment by nickheyvaert** [comment]
@nerrad Any chance this merge is going to happen in the near future?

**Comment by nerrad** [comment]
Hi @nickheyvaert sorry for the delay, I'm not the PM for EE so for the most part, I only work on what is assigned to me.  I took a quick gander and since this is fairly straightforward I've merged it into a branch in our repo and have made a few additional changes.  The branch is https://github.com/eventespresso/event-espresso-core/tree/BUG/11369/fix-event-list-table-column-methods

(internal ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11369)

Once that passes code review and our team testing it'll get merged into master.

Thanks for the pull request and pointing out this issue 👍

**Pull request merged**
