### PR TITLE
Gdpr/phone not remoevd

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves
https://github.com/eventespresso/event-espresso-core/issues/509

## Why do you think these changes are needed in Event Espresso core instead of being put in an add-on?
EE core code

## How has this been tested

Make sure you have a registration with a phone number. Create a data erasure request for that user's email. Erase their data. Their phone number should be erased too

## Checklist

* [x] I have added a changelog entry for this pull request
* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [ ] My code accounts for when the site is Maintenance Mode (MM2 especially disallows usage of models) --> I actually realized there's an issue with this, but the issue also exists in master, see https://github.com/eventespresso/event-espresso-core/pull/568

### CODE REVIEW

**Comment by Pebblo** [comment]
I've confirmed this works as expected and the phone number is now removed.

@mnelson4 just to note, the change log item looks incorrect above.

**Comment by mnelson4** [comment]
> @mnelson4 just to note, the change log item looks incorrect above.

ooOOups, ya. I'll fix that

**Comment by mnelson4** [comment]
another review required since previous changes. I don't think re-testing is necessary though, right?

**Comment by nerrad** [comment]
No I don't think retesting is needed.

**Pull request merged**
