### PR TITLE
Enable copy attendee info at admin

### PR DESCRIPTION
**Pull request by raphaelkross**
## Problem this Pull Request solves

Solves https://github.com/eventespresso/event-espresso-core/issues/188 adding the copy attendee at admin registration page.

## How has this been tested

At Dashboard/admin, add new Registration to an event (that asks for more info for extra attendees) and add more than 1 ticket.

At Registration page on Admin, the Copy Info for other Attendee should be displayed and work same way than Frontend Checkout.

- When fields are not filled, validation errors should be displayed and you can't check the toggle.
- After valid info is filled, the info will be copied to other attendee fields.

A new filter is added in case customer wants to override the option from admin to, for example, enable the copy attendee only at admin (using a is_admin inside the filter):

```
FHEE__EE_SPCO_Reg_Step_Attendee_Information___registrations_reg_form___printCopyInfo
```

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by joshfeck** [comment]
I tested the feature and it works great. 

There may be an issue with the filter hook though. If I add a filter function to return false, the copy attendee information section still displays. 

It looks like we might need the filter hook near the end of the _registrations_reg_form method?

**Comment by raphaelkross** [comment]
@joshfeck hmmm that's true - I've moved the filter and now to make this work you would use some code like:

```php
add_filter( 'FHEE__EE_SPCO_Reg_Step_Attendee_Information___registrations_reg_form___printCopyInfo', function( $flag ) {
    if ( is_admin() ) {
        return true;
    }

    return $flag;
});
```

In case the customer wants to display it only at admin and at FE just follow the Registration Form settings.

**Comment by joshfeck** [comment]
The new location works and I think we'll want to pass that $attendee_nmbr variable as an additional argument, which will allow for only showing the copy form in the admin **and** only when there are additional attendee forms.

e.g.
`add_filter(
    'FHEE__EE_SPCO_Reg_Step_Attendee_Information___registrations_reg_form___printCopyInfo',
    'toggle_print_copy_info',
    10,
    2
);

function toggle_print_copy_info($flag, $attendee_nmbr) {
    if (is_admin() && $attendee_nmbr > 1) {
        return true;
    }
    return $flag;
}`

If the above is OK with you, then this is ready to merge. (I've tested this again).

**Comment by raphaelkross** [comment]
@joshfeck 👍 makes sense for me! Nice idea!

**Pull request merged**
