### PR TITLE
Fixed warning during registration reports in PHP 7.2

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

https://github.com/eventespresso/event-espresso-core/issues/687#issuecomment-421144956
Although I couldn't reproduce the issue in PHP 7.2.10 (yes with WP_DEBUG true), so I'm not 100% positive this really fixes it. I gather this happens in PHP 7.2 when we call `count(null)` (among other non-array, non-countable things; see https://stackoverflow.com/questions/50898330/grizzle-error-count-parameter-must-be-an-array-or-an-object-that-implements-c). I don't see how the warning was coming up, because the item we're counting in that line should always be an array (unless something is filtering it and changing it into something different).

## How has this been tested

* [ ] With a few registrations in your system, run a registrations report. There should be no warnings.

## Checklist

* [ ] I have added a changelog entry for this pull request
* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by mnelson4** [comment]
oups, ya thanks @tn3rb.
So this is ready for testing. @lorenzocaum do  you want to test this one?

**Comment by lorenzocaum** [comment]
Hi Mike, I don't have a test site running PHP 7.2. Can this be cherry picked onto Event Smart staging for testing?

**Comment by mnelson4** [comment]
> Hi Mike, I don't have a test site running PHP 7.2. Can this be cherry picked onto Event Smart staging for testing?

Done! Please note that this change will be removed next time EE core is updated on ES

**Comment by lorenzocaum** [comment]
Thanks Mike. I ran a couple of registration reports on different websites on staging and checked the CSV files. Then I checked Log entries. I didn't see the PHP warnings.

Please merge

**Pull request merged**
