### PR TITLE
Fix Recaptcha Issue

### PR DESCRIPTION
**Pull request by hoseinrafiei**
Fixes: https://github.com/eventespresso/event-espresso-core/issues/3879

Screen Shot 2022-06-15 at 19 04 41

Please proceed with steps explained in the issue topic and make sure that the issue won't happen for you.

### CODE REVIEW

**Review by tn3rb — APPROVED** [review]
changes look great 💯 
this will need to be tested heavily before it can be merged though

**Review by knazart — APPROVED** [review]

**Comment by knazart** [comment]
This also fixes the https://github.com/eventespresso/eventsmart.com-website/issues/973, so we might not need the https://github.com/eventespresso/event-espresso-core/pull/3841 anymore.

**Comment by hoseinrafiei** [comment]
@Saam01

Please test this branch. It's related to recaptcha feature.
Please test whole different aspects of it including backend configuration menus, registration process, ticket selector, iframe, etc.

Also please use the different configurations of recaptcha to make sue all the options are working correctly.

**Comment by garthkoyle** [comment]
I tested: 

* [x] the recaptcha settings page saved as expected
* [x] basic registration
* [x] TS Embed registration
* [x] HTML Embed registration
* [x] I also tested with invisible recaptcha on the TS and Reg form

**Pull request merged**
