### PR TITLE
Fix DMS weirdness because event table selections overwriting attendee table selections

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Fixed several errors during the EE 4.1 migration (like missing address info on migrated attendees, incorrect registration counts, answers all for the same attendee, etc). 
These errors arose because some EE3 event table values (eg address, city, phone) were being used instead of the attendee table values  (ever since we started avoiding migrating attendees for deleted events). The fix involved just making sure we ignore the event table's values.

## How has this been tested

* [x] In EE3, create multiple question groups, an event that uses all question groups for primary and additional attendees, and allows group registrations and requires their full registration info. 
* Register a few times for that event.
* Also, create and register for another event, then trash that event.
* Deactivate EE3 and activate this branch of EE4 and run the migrations.
* Verify the new registrations all have the correct answers to the custom questions, the database column's `REG_count` is correct, their address info is populated correctly on the attendee, and they're for the correct transactions.
* Also verify that the attendees for the deleted event were NOT imported into EE4.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by mnelson4** [comment]
Thanks @tn3rb, passing for testing.

**Comment by joshfeck** [comment]
Related issue #1034

**Comment by joshfeck** [comment]
Tested so far and I can see that the issues reported in #1034 are fixed with this branch. Will continue testing through the checklist.

**Comment by joshfeck** [comment]
Finished testing the checklist

**Pull request merged**
