### PR TITLE
Bug/fix display strategies extra trs and tds

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Fixes a few places where we had tr tags directly under td tags, which was invalid HTML. See https://github.com/eventespresso/event-espresso-core/issues/1181

## How has this been tested

* [x] At least in Firefox, if you open the payment methods page, there shouldn't be any tr or td tags highlighted in red (like in the screenshot from https://github.com/eventespresso/event-espresso-core/issues/1181)
* [ ] ditto for the registration details page

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by mnelson4** [comment]
I thought about removing the redundant text here: https://drive.google.com/a/eventespresso.com/file/d/1gMojKswqgVXc7-sDML2ARH4Ysbx-z6MR/view?usp=drivesdk. But if anyone objects we can leave it; nobody has complained, to my knowledge.

**Comment by joshfeck** [comment]
The payment options page checks out. I found one other place on the registration details page that has a tr tag within a td, should that also get fixed?

Screen Shot 2019-05-08 at 12 53 34 PM

**Comment by mnelson4** [comment]
oh ya totally, thanks...

**Comment by mnelson4** [comment]
Seeing how this latest commit changed some JS too, I think it merits a re-review

**Pull request merged**
