### PR TITLE
Normalize main plugin file

### PR DESCRIPTION
**Pull request by szepeviktor**
and fix comments in PHPDoc blocks

### CODE REVIEW

**Comment by tn3rb** [comment]
Some customers will download a new version of the plugin and activate it while the previous version is still active.

Put a copy of EE (maybe a tagged older version, although doesn't really matter) into another folder, so that you have two versions of EE in your plugins folder. Then activate both of them. You'll see why the code in this file was the way it was.

😄

**Comment by szepeviktor** [comment]
Okay. That is stranger than I can bear.
I leave it up to you.

I think with these `return`-s the version still remains active but nothing is loaded except the admin notice.

**Comment by joshfeck** [comment]
Likely it wasn't intended for this to happen:

```
[05-Feb-2020 23:20:32 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function espresso_deactivate_plugin() in /Applications/MAMP/htdocs/ee4/wp-content/plugins/32-core/espresso.php:64
Stack trace:
#0 /Applications/MAMP/htdocs/ee4/wp-includes/class-wp-hook.php(286): espresso_duplicate_plugin_error()
#1 /Applications/MAMP/htdocs/ee4/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#2 /Applications/MAMP/htdocs/ee4/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /Applications/MAMP/htdocs/ee4/wp-admin/admin-header.php(281): do_action('admin_notices')
#4 /Applications/MAMP/htdocs/ee4/wp-admin/plugins.php(481): require_once('/Applications/M...')
#5 {main}
  thrown in /Applications/MAMP/htdocs/ee4/wp-content/plugins/32-core/espresso.php on line 64
```

**Comment by szepeviktor** [comment]
I am really bad an reading and writing non-OOP code,
an not so bad at OOP.

Just pushed another commit.

Really definitions and side-effects should not live in one file.

**Comment by szepeviktor** [comment]
Now we have a few functions and the juicy stuff:

```php
define('EVENT_ESPRESSO_MAIN_FILE', __FILE__);
define('EE_MIN_PHP_VER_REQUIRED', '5.4.0');

if (function_exists('espresso_version')) {
    add_action('admin_notices', 'espresso_duplicate_plugin_error', 1, 0);
    return;
}

if (! version_compare(PHP_VERSION, EE_MIN_PHP_VER_REQUIRED, '>=')) {
    add_action('admin_notices', 'espresso_minimum_php_version_error', 1, 0);
    return;
}

register_activation_hook(EVENT_ESPRESSO_MAIN_FILE, 'espresso_plugin_activation');

require_once __DIR__ . '/core/bootstrap_espresso.php';
bootstrap_espresso();
```

**Comment by szepeviktor** [comment]
Oh no!

This if-function-exists thinking make my brain stop :)
I'm sorry.

**Comment by szepeviktor** [comment]
espresso_version is defined *before* `function_exists('espresso_version')` ...

**Comment by szepeviktor** [comment]
Actually I've intended to fix the structure of the plugin to run static analysis by @phpstan.

**Pull request closed without merging**
