### PR TITLE
Add an action for the check in status is toggle to either checked_in or checked_out

### PR DESCRIPTION
**Pull request by Pebblo**
This PR just adds 2 actions:

```
AHEE__EE_Registration__toggle_checkin_status__checked_in
AHEE__EE_Registration__toggle_checkin_status__checked_out
```

and passes the EE_Registration and DTT_ID to those actions incase needed.

## How has this been tested
I use a helper function to write content to the logs:

```
if ( ! function_exists('write_log')) {
   function write_log ( $log )  {
      if ( is_array( $log ) || is_object( $log ) ) {
         error_log( print_r( $log, true ) );
      } else {
         error_log( $log );
      }
   }
}
```

Then just do something like:

```
add_action('AHEE__EE_Registration__toggle_checkin_status__checked_in', 'tw_ee_toggle_checkin_test', 10, 2);
function tw_ee_toggle_checkin_test($Reg, $DTT_ID) {
    write_log(
        array(
          'REG_ID' => $Reg->ID(),
          'DTT_ID' => $DTT_ID,
          'action' => 'checked_in'
        )
    );
}

add_action('AHEE__EE_Registration__toggle_checkin_status__checked_out', 'tw_ee_toggle_checkout_test', 10, 2);
function tw_ee_toggle_checkout_test($Reg, $DTT_ID) {
    write_log(
        array(
          'REG_ID' => $Reg->ID(),
          'DTT_ID' => $DTT_ID,
          'action' => 'checked_out'
        )
    );
}
```

Now toggle checkins o a registration and check your error logs, if you are using [THIS CODE](https://eventespresso.com/wiki/troubleshooting-checklist/#wpdebug) in your wp-config.php file you should see entries in /wp-content/debug.log.

Make sure when you toggle a checkin status to checked_in you see the `'action' => 'checked_in'` log entry, when you check out you should then see 'action' => 'checked_out'

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.
* [ ] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Review by tn3rb — APPROVED** [review]
Looks Great 💯 

nice use of a dynamic filter name

**Comment by sethshoultes** [comment]
@Pebblo I am getting a syntax error with the code samples on this line:
`'REG_ID' => $Reg->ID(),`

Error:
`Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' `

**Comment by Pebblo** [comment]
Syntax error was my test function, it was missing array() around the values, thats fixed.

On testing this I released it wasn't working! Turned out I used single quotes for the action name which means the action was literally `'AHEE__EE_Registration__toggle_checkin_status__{$checked_status}'`

Switched that out for double quotes so the PHP variable parses! No need for a re-review on this.

Try now please Seth.

**Comment by sethshoultes** [comment]
This seems to be working. Here are the contents of my log:
Screen Shot 2020-11-24 at 8 56 45 AM

Please merge.

**Pull request merged**
