### PR TITLE
Fixed issue of creating / updating question group with duplicate identifier.

### PR DESCRIPTION
**Pull request by hoseinrafiei**
Fixes https://github.com/eventespresso/event-espresso-core/issues/3798 issue.

### CODE REVIEW

**Comment by hoseinrafiei** [comment]
@mohdshakeel Please test the issue on this branch (`fix/question-group-identifier`) and let me know the results.

**Comment by mohdshakeel** [comment]
Thanks, Its working perfect now.

**Comment by hoseinrafiei** [comment]
@tn3rb Could you please check and confirm the changes?

**Review by tn3rb — APPROVED** [review]
Looks Great 💯

**Pull request merged**
