### PR TITLE
Filter getTickets() Return Value

### PR DESCRIPTION
**Pull request by tn3rb**
plz see: #3387 

This PR does exactly what the the title says

### CODE REVIEW

**Review by Pebblo — APPROVED** [review]
LGTM

**Comment by Pebblo** [comment]
Apologies for the delay on this, got a little sidetracked!

**Comment by tn3rb** [comment]
no worries about the delay.

Do you know how to rebase Tony?
Rebasing essentially replays the commits in a branch onto the targeted base as if they were just done for the first time. The only catch is that you never want to do it with branches that have been shared extensively because a rebased branch can not be merged into a checked out version of itself. You have to delete the local and re-checkout the rebased origin (so NEVER rebase master). Here's a decent explanation if you want more info: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

Anyways, in the future, can you plz rebase bug fix and feature branches on top of their targeted base branch instead of performing a standard merge. The end result is a much cleaner and easier to deal with.

**Comment by Pebblo** [comment]
Oh, sorry. I just used the GitHub UI and clicked updated branch, the intention was to let it run through the checks before you got online.

I'll find out how to rebase in SmartGit, ta.

**Pull request merged**
