### PR TITLE
Add filters required for #313

### PR DESCRIPTION
**Pull request by mnelson4**
Adds paypal smart buttons. See https://github.com/eventespresso/event-espresso-core/issues/313

### CODE REVIEW

**Comment by mnelson4** [comment]
actually, we're going to be making this an add-on. At very least initially, so it can be developed independently of the rest of EE and not be placed in front of ALL our users until it's had some more small-scale user testing. We'll re-evaluate whether this should go into core afterwards

**Comment by mnelson4** [comment]
Seeing how PayPal Smart Buttons will be a separate add-on, I'm just going to use this for the filters I needed for that. (Yes, I may end up creating separate PRs for each, but I'm first making sure it will meet the add-on's needs)

**Comment by mnelson4** [comment]
This is required for https://github.com/eventespresso/eea-paypal-smart-buttons/pull/1. 
## What changed
So, this just adds a few filters, and refactored EE_Radio_Button_Display_Strategy to use the less-old method `_attributes_string()` which makes the attributes more maliable, standardized, and filtered... although it turned out that didn't provide what I needed for the new gateway integration, it seemed like a good thing to leave anyway. What's more that code is unit tested so it helped protect from regression there.

## Testing
* [ ] Verify radio buttons work the same as ever. Eg, the payment method select radio-box input in SPCO should still work. 
* [ ] Custom questions using radio buttons should still work. Test having required and non-required radio button questions. Those should all work the same as before.

**Comment by sethshoultes** [comment]
Testing notes check out.

@tn3rb can you please review this so I can get it merged to core?

**Pull request merged**
