### PR TITLE
make sure validation defaults are initialized when loading billing forms

### PR DESCRIPTION
**Pull request by joshfeck**
## Problem this Pull Request solves

Discovered this while testing the new Stripe add-on. What was happening was all required fields on the billing form were highlighted with green, which shouldn't happen when the field is empty.
Screen Shot 2019-08-15 at 3 58 03 PM

After a quick chat about this in Slack, @tn3rb came up with the solution in this PR.

## How has this been tested

Test SPCO reg form, there should be no change to the validation behavior.
then test a few onsite payment method forms, switching to and from other PMs. Blank required fields shouldn't initially be highlighted with green. They should be highlighted with green only when complete & pass validation.

Screen Shot 2019-08-15 at 5 49 40 PM

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by tn3rb** [comment]
> were both removing then adding the class ee-needs-value just to double-check its set

that's correct, as far as I know there is no built-in logic for preventing duplicates. 

from the jQuery docs at https://api.jquery.com/addClass/:

```
It's important to note that this method does not replace a class. It simply adds the class, appending it to any which may already be assigned to the elements.
```

**Comment by sethshoultes** [comment]
Here's how it looks using Authorize.net:
Registration Checkout – Events by Espresso 2019-08-15 21-33-24

@Pebblo can you please check a couple of the other gateways?

**Comment by sethshoultes** [comment]
Tested with Stripe Elements and the payment forms look correct now:
Registration Checkout – Events by Espresso 2019-08-16 05-47-01

**Comment by Pebblo** [comment]
Looks good to me!

Phone fields don't seem to validate when auto-filled - https://monosnap.com/file/fMJe7Lg8V8HkFQGR8561zi2eOtb4o7

It doesn't prevent the payment and validates on click but just thought I'd mention it.

Other than that I've not had any issues with the payment methods I tested

Infusionsoft, Vanco, AIM, Quickbooks all work fine.

**Pull request merged**
