### PR TITLE
Kses - Part 23

### PR DESCRIPTION
**Pull request by hoseinrafiei**
Recreation of https://github.com/eventespresso/event-espresso-core/pull/4026.
Checklist: https://trello.com/c/2NABkcqc/1169-ee4-core-testing-checklist-pr-4026

### CODE REVIEW

**Comment by hoseinrafiei** [comment]
@Saam01 Please check this PR using the https://trello.com/c/2NABkcqc/1169-ee4-core-testing-checklist-pr-4026 checklist. The changes of this PR mainly focus on the configuration forms of backend menus and widgets.

**Comment by Saam01** [comment]
Error with messages when we register an event:

https://user-images.githubusercontent.com/99984614/188885018-5d7c8b7c-8456-47ae-825d-e1495e80d2c4.mp4

WordPress-›-Error

**Review by tn3rb — APPROVED** [review]

**Comment by Saam01** [comment]
[This](https://github.com/eventespresso/event-espresso-core/pull/4046#issuecomment-1239364237) seems to be working fine today

**Comment by Saam01** [comment]
@hoseinrafiei I've finished this checklist.

**Pull request merged**
