### PR TITLE
Kses - Part 18

### PR DESCRIPTION
**Pull request by hoseinrafiei**
Closes https://github.com/eventespresso/event-espresso-core/issues/3738 issue.
Escaped the remaining variables.

### CODE REVIEW

**Review by tn3rb — APPROVED** [review]
Looks Good 👍🏻

**Comment by garthkoyle** [comment]
@hoseinrafiei do you have any direction on which area of Event Espresso we should focus testing, or everything again?

Has a checklist been created? @Saam01

**Comment by Saam01** [comment]
I've finished checking the PDF contents generation.

Found an issue with PDF which I mentioned in #21

**Comment by hoseinrafiei** [comment]
Since the reported issue is general and can be reproduced in `master` branch, I'm merging this.

**Pull request merged**
