### PR TITLE
Fix Save Issue of Critical Pages Form

### PR DESCRIPTION
**Pull request by hoseinrafiei**
Fixes https://github.com/eventespresso/event-espresso-core/issues/3888 issue.

Before Change

After Change

### CODE REVIEW

**Comment by hoseinrafiei** [comment]
@tn3rb

`$this->core_config` variable was null in `_update_espresso_page_settings` function. I fixed the issue by defining the variable but I'm curious to find how it was working before and what change created this problem.

I checked the file history and didn't find anything suspicious in the `admin_pages/general_settings/General_Settings_Admin_Page.core.php` file. So I guess maybe recently we changed something in higher level and a little worry about the affects of this change on some other parts of the EE.

Do you think that we should investigate and find the root cause of the problem?

**Comment by tn3rb** [comment]
re:
> Do you think that we should investigate and find the root cause of the problem?

i think it's because originally, the code was referencing `EE_Registry::instance()->CFG->core` everywhere directly and I replaced it with a class property so that it could eventually be injected at run time instead of being hard coupled.  But i missed that the `admin_init()` method isn't called on that update request (still surprised at that)

**Comment by hoseinrafiei** [comment]
> this is fine, another approach would be to remove this line, as well as the duplicate in `admin_init()` and then place it in an earlier method call like `_init_page_props()`

Good point. Done 👍

**Review by tn3rb — APPROVED** [review]
yup 👍🏻  plz just verify it still works

**Comment by hoseinrafiei** [comment]
> yup 👍🏻 plz just verify it still works

Yes, already checked.

**Comment by hoseinrafiei** [comment]
@Saam01

Please test this one. It is related to the registration as well. Please check the backend menu and set new pages (with shortcodes) and test whole registration process and post registration process (invoicing, edit, etc) to make sure that it works and new pages are applying.

**Comment by garthkoyle** [comment]
This looks to be working fine now (video): https://www.screencast.com/t/gXTMHQU89EN

**Comment by Saam01** [comment]
Feature seems to be working fine for me also.

**Pull request merged**
