### PR TITLE
Fix PayPal Pro gateway to send correct value for the State/Province field, fixes #453

### LINKED ISSUE #453: Fix PayPal Pro gateway so it sends the correct value for the State/Province field
Currently the PayPal Pro gateway sends the full state/province name instead of the expected state/province code. Examples:

https://developer.paypal.com/docs/classic/api/state_codes/#usa
https://developer.paypal.com/docs/classic/api/state_codes/#canada

### PR DESCRIPTION
**Pull request by joshfeck**
## Problem this Pull Request solves
See #453 

## How has this been tested

- [x] Test payments using PayPal Pro. Do one payment where the Registration form includes address fields (and complete those fields). Do another payment where the registration form does not include address fields.

- [x] After testing payments, check the Transaction records and verify billing info's State field looks correct (it should show the full state/province name).

- [x] Then check the PayPal transactions admin and verify the shipping address now includes something for the State field.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by joshfeck** [comment]
The related issue on GitHub has the links:

https://developer.paypal.com/docs/classic/api/state_codes/#canada
https://developer.paypal.com/docs/classic/api/state_codes/#usa

**Comment by mnelson4** [comment]
d'oh! I was just updating my comment mentioning the same thing.
Most importantly though @joshfeck, I was just suggesting
> We should probably test what happens if an EE state's abbreviation doesn't match the PayPal abbreviation. I'm guessing it will be the same as what's currently happening (so this change can only be an improvement)

**Comment by joshfeck** [comment]
retested Mike's change, with all my now-apparently-unnecessary changes removed.

**Comment by joshfeck** [comment]
Screen Shot 2019-10-01 at 12 58 37 PM

**Pull request merged**
