### PR TITLE
Turn off, but filter link to the "Failed Transactions" list table Fixes #737

### LINKED ISSUE #737: Remove the Failed transactions link from Transactions overview screen
**Summary**
On the transactions overview screen, there is a link that shows Failed transactions. An event organizer can't reach out to the attendee because there is no information connected. And this is difficult to explain to event organizers because it seems like there is a problem with the system.

I think that link to the view should be removed.

If you think there is value in having it appear for some event organizers, then maybe have a filter to restore it.

**Other notes**
- See recent discussion on the P2 and those linked from it (http://p2.eventespresso.com/2018/10/15/this-week-in-event-espresso-october-14-october-20/#comment-19812)
- https://events.codebasehq.com/projects/event-espresso/tickets/7317
- https://events.codebasehq.com/projects/event-espresso/tickets/7412

### PR DESCRIPTION
**Pull request by tn3rb**
## Problem this Pull Request solves
Fixes #737

Filters whether a link to the "Failed Transactions" list table appears on the Transactions Admin Page list table.
 display can be turned back on via the following:

```php
add_filter(
     'FHEE__Transactions_Admin_Page___set_list_table_views_default__display_failed',
     '__return_true'
);
```

## How has this been tested
browser based monkey testing

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by tn3rb** [comment]
## testing

- visit the Transactions admin list table
- [ ] confirm that the link to the "Failed Transactions" list table no longer appears
- add the following filter to an appropriate location in your site code

```php
add_filter(
     'FHEE__Transactions_Admin_Page___set_list_table_views_default__display_failed',
     '__return_true'
);
```

- refresh the Transactions admin list table
- [ ] confirm that the link to the "Failed Transactions" list table appears again

**Comment by Pebblo** [comment]
`add_filter(
     'FHEE__Transactions_Admin_Page___set_list_table_views_default__display_failed_txns_list',
     '__return_true'
);`

Is the correct filter, (which works), but the comments in the code show another.

**Comment by sethshoultes** [comment]
@Pebblo okay, thanks! That worked.

**Comment by Pebblo** [comment]
The comments (and possibly the filter name) need to be updated either way as one uses one filter name and then the code uses another.

So I've switched this back to please fix so it doesn't just get merged in without the above.

**Comment by joshfeck** [comment]
@tn3rb I went ahead and updated the DocBlock so the filter name matches. If this looks good then it's ready to merge.

**Comment by tn3rb** [comment]
oops... sry about the filter name... forgot that it changed :facepalm:

**Pull request merged**
