### PR TITLE
Redirect SPCO if Payment has Redirect URL

### PR DESCRIPTION
**Pull request by tn3rb**
Old work branch of Michael's that is still valid and should be merged.

comment from Michael on commit:

> instead of relying on the gateways type to determine if SPCO should redirect, use whether or not the payment has a redirect URL

### CODE REVIEW

**Review by knazart — APPROVED** [review]

**Comment by tn3rb** [comment]
testing:

looks like the following gateways set a redirect url:

- Authorize.net
- PayPal Standard
- PayPal Express

there might be others I don't currently have installed that do so as well, but for 100% thoroughness, ALL offsite gateways should be tested

**Comment by garthkoyle** [comment]
@Pebblo and @knazart is the redirect URL something that's used post-transaction completion? Where is that set in EE or is that in the account settings?

**Comment by tn3rb** [comment]
redirect URL is hardcoded in the payment method code
it's where the browser sends you when you go to an offsite gateway

**Comment by joaovictorangeline** [comment]
@tn3rb How can I test this?

**Comment by tn3rb** [comment]
@joaovictorangeline 
you'll need to setup each of the following payment methods:
- Authorize.net
- PayPal Standard
- PayPal Express

then test a registration using each payment method.

As long as everything redirects correctly and you end up at the Thank You page (you may have to manually click something at the payment gateway site in order to return) then it should be good to go

**Comment by joaovictorangeline** [comment]
Tested and it seems to be working fine.
Tested with Authorize.net, PayPal Standard, and PayPal express. 💯

**Comment by Pebblo** [comment]
Also confirmed this worked fine with the above payment methods.

I also tested Mollie as iirc it does something weird with the redirect. Works fine.

**Pull request merged**
