### PR TITLE
delays enqueueing reg steps JS until wp_enqueue_scripts and adm…

### PR DESCRIPTION
**Pull request by mnelson4**
…ueue_scripts

## Problem this Pull Request solves

Delays registering scripts in SPCO until `wp_enqueue_scripts` and `admin_enqueue_scripts`. This allows other scripts to wait until those hookpoints to register too, which is just a bit more orderly and proper. (Otherwise everything ends up happening on different priorities of `init` which is messy.)
Specifically, this helps with https://github.com/eventespresso/eea-stripe-gateway/pull/28.

## How has this been tested

* [ ] Make a normal registration
* [ ] Register using several payment method that uses Javascript, like Stripe, Braintree, PayPal Smart Buttons, etc. (This ticket affects when their Javascript gets loaded, so we should just double-check it's still getting loaded a-ok.)

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by joshfeck** [comment]
I've been testing this branch on a local server and it seems that PayPal Express with Smart buttons payments are having some trouble. I'm going to try testing this branch on another server to rule out any potential troubles with the local server.

**Comment by joshfeck** [comment]
I've got the PayPal smart buttons issue sorted out and have been testing this branch and haven't seen any differences with the payment methods loading/working. So I'd say we're good to merge.

**Comment by mnelson4** [comment]
Oups sorry I missed that this was ready for merge @joshfeck. I think I will retest myself (double-check nothing got broken with changes to EE master) and then merge

**Comment by mnelson4** [comment]
I didn't see any issues with this branch itself, although I did discover an issue in PayPal Smart buttons while testing this :https://github.com/eventespresso/eea-paypal-smart-buttons/issues/48

**Pull request merged**
