### PR TITLE
Bug/3607 max attendeezzz

### LINKED ISSUE #3607: Fix incorrect number of tickets selected when max atendz per order is set to 1
I think this is linked to: #3597

Create an event with 'Maximum number of tickets allowed per order for this event:' set to 1.

On that event have multiple ticket types.

Selecting the first ticket type, works.

Selecting ticket type 2+ shows:

> An error has occurred:
> You have attempted to purchase n tickets.
> The registration limit for this event is 1 ticket per registration, therefore the total number of tickets you may purchase at a time can not exceed 1.

n being the ticket type selected.

So selecting the third ticket type on the TS selects 3 tickets, 4th = 4 tickets etc etc.

E.g: 
image

### PR DESCRIPTION
**Pull request by tn3rb**
This PR:

- closes #3607 
- fixes potential recursion in request param sanitizer when delimiter is set
- retrieves correct ticket qty when max attendees for an event is set to 1

### CODE REVIEW

**Review by knazart — APPROVED** [review]
👍

**Comment by tn3rb** [comment]
@Pebblo 
OOF! Sorry about that. Made a dum dum mistake but it's fixed now. 
Thanks for checking the regular ticket selector again and keeping me honest 👍🏻

**Review by knazart — APPROVED** [review]

**Comment by Pebblo** [comment]
This fixes the current issue and I thought all was ok!

However, Brent mentioned testing 'Dude Wheres My Ticket Selector' (DWMTS) when he passed this over and the testing for the above ([HERE](https://monosnap.com/file/sRFPpV54lBkApfvS5j9m5t4t3kECGq)) is not what I consider DWMTS so I wouldn't have caught this, good shout!

---

Create an event with **ONE** ticket type and make sure that ticket is a free ticket.

Set Max attendees on the event to 1.

When you register onto the event it will look like this: https://monosnap.com/file/2lay2UGnsLtpVd3E2P3D1vqoJ1ri5L

Hit the register now button, you'll get: 

> An error has occurred:
> You need to select a ticket quantity before you can proceed.
> ProcessTicketSelector - addTicketsToCart - 460

See here: https://monosnap.com/file/STJ1XMPvXw3P0XTmb4BrmeuvIeg11X

**Comment by tn3rb** [comment]
dang it.. ya I used the DWMTS term incorrectly, but good thing i guess 😕

**Comment by Pebblo** [comment]
Thanks, Brent!

Looks like that's fixed them all.

**Pull request merged**
