### PR TITLE
Fix bug with template pack switching

### PR DESCRIPTION
**Pull request by nerrad**
## Problem this Pull Request solves

In https://eventespresso.com/topic/message-template-pack-issues/ an issue was reported with errors on switching template packs.  Although the template pack switching IS working, there's an error due to incorrect error detection and return values on the successful switch. 

I also fixed an issue where the custom template pack was showing its label twice in the dropdown after being switched.

## How has this been tested

* [x] Copy into your plugins folder and activate the Message Template Pack add-on example found in the `tests/mocks/addons` folder of event-espresso-core.
* [x] Edit a default template that this pack is active for (payment_declined, payment, payment_refund, payment_reminder or newsletter)
* [x] Switch to the template pack (using the switcher in the sidebar) and verify there are no errors and the template switched successfully.
* [x] Verify that you can switch back
* [x] verify normal template resets using the blue "Reset Templates" button works okay.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by nerrad** [comment]
> Although I would indent lines 985 and 986 one more time.
Ya I _did_ originally have them indented like you suggested but (and I don't know why) my IDE and linting both are not happy when I do so.  So leaving as is.

**Comment by nerrad** [comment]
@sethshoultes this is ready for testing (see testing notes in description for pull)

**Comment by sethshoultes** [comment]
@joshfeck can you please test this?

**Comment by joshfeck** [comment]
Checks pass, this is ready for merging.

**Pull request merged**
