### PR TITLE
Bug/add limits to cron queries

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Helps with timeouts when there are sites with lots of expired, incomplete transactions. See https://github.com/eventespresso/event-espresso-core/issues/2035

## How has this been tested

* [x] View an event and submit a ticket purchase. But don't enter any info. In the DB, change its transaction's `TXN_timestamp` to be a year ago, then run the cron task `AHEE__EE_Cron_Tasks__clean_up_junk_transactions` (see previous item`). The transaction should get deleted
* [x] Verify old messages are still deleted as they were before (after a month by default, although you can use the filter `FHEE__EEM_Message__delete_old_messages__time_to_leave_alone` to set a different amount of time to wait, in seconds)

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.
* [x] My code accounts for when the site is in Maintenance Mode (MM2 especially disallows usage of models)

### CODE REVIEW

**Comment by tn3rb** [comment]
> is it a problem if $transactions_not_in_progress is only a subset of all the incomplete transactions whose session has expired, instead of the complete list?
> Is it necessary for EED_Ticket_Sales_Monitor::release_reservations_for_tickets) that its list of $valid_reserved_tickets (which is actually line items for ticket purchases) be generated from the complete list of incomplete transactions whose session expired?

yes and yes

why? Because it won't ever reset reserved tickets for anything not returned in that initial query now.

I think in order for this to work properly, we will need to do the following:

- add an offset value to the query in `EEM_Transaction::_get_transactions_in_progress()`
- allow the offset and limit values to be passed in to the above method as well as `get_transactions_not_in_progress()`
- refactor `EED_Ticket_Sales_Monitor::reset_reservation_counts()` so that it runs recursively, passing values for limit and offset to the above until no more records are returned
- likely have to run those queries and reserved count resets in additional requests to avoid timeouts

**Comment by mnelson4** [comment]
Thanks Brent. So as I understand it, if we limited `EEM_Transaction::_get_transactions_in_progress()`, we could only release tickets for the latest 1000 expired transactions, at least until they're deleted (which happens after 1 week.)
So that change wouldn't really work.
If we want me to continue this, I think making `\EED_Ticket_Sales_Monitor::reset_reservation_counts` more efficient (avoiding grabbing whole transaction objects, instead just grab IDs or something; and avoiding retrieving the grand total line items when all we want are the ticket line items) would be the best next step, before trying to do batches etc.
Also, maybe making the cron task run more frequently for high-traffic sites (like every half hour instead of every hour) should halve the amount of work we need to do each time it runs.
Anyways, I've reverted the part of this commit that wasn't ready, but the stuff that is ready I left in here and am passing off for testing

**Comment by joshfeck** [comment]
I tested the AHEE__EE_Cron_Tasks__clean_up_junk_transactions and everything went well. If you wanted to merge what we have so far that will be fine.

Could you also look into the `EEM_Message::instance()->delete_old_messages()` query, maybe that one can have a limit?

**Comment by mnelson4** [comment]
> Could you also look into the EEM_Message::instance()->delete_old_messages() query, maybe that one can have a limit?

Oh sure, I didn't notice that one because it's not scheduled from `EE_Cron_Task` like the others. I set the limit to 2000 because it only runs daily and we also should avoid falling behind the number of messages that are actually sent (as is, I think if there's a big event which sells thousands of tickets in a day, it should just take a few days to catch up and delete all the messages that got generated.)

**Comment by mnelson4** [comment]
On a related ticket, Nazar and I were discussing basically the exact same issue for ES, where I advocating to fetch the OLDEST first... So it makes sense to delete the oldest junk transaction first too.
Sorry, this idea should probably be verified too (even though it's just a couple characters difference in the commit.

**Comment by mnelson4** [comment]
This should get Josh's blessing again before merging (since you last approved it, I added your suggestion of limiting the messages cleanup task, and tweaked the other code too)

**Comment by joshfeck** [comment]
tested message activity log cleanup, it still works

**Pull request merged**
